### ISSUE TITLE
최종 선택 여부 판단하는 bool 값

### ISSUE THREAD

**Issue by junsarakill** [junsarakill/mtvs3rd#15]
bs_playerstate 에서 void SetIsFinalSelect(bool value); 로 값 설정 
또는 IS_FINAL_SELECT = true;
로 해도됨.

현재 메인에 변수 추가함.

**Comment by ParkSoonHong** [comment]
bs_playerstate 에서 void SetIsFinalSelect(bool value); 
이걸로 마지막 포탈에 탔을때 true 넘겨줬어

**Comment by junsarakill** [comment]
작동 확인
