### ISSUE TITLE
최종 선택

### ISSUE THREAD

**Issue by ParkSoonHong** [junsarakill/mtvs3rd#16]
APSH_Mtvs3rdGameModBase에 있는
 LastChoice(int FromId, int ToId) 함수 실행시 바로 매칭 성공 표시를 영화관 스크린에
 
 매칭 되었습니다

남자 : 여자 

로 표시중

단 현재 프로토 테스트를 위하여 무조건 성공하고 
매칭되었습니다
영철 도레미

로 실행됨

**Comment by junsarakill** [comment]
혹시 내가 
1. 플레이어 -> 더미
2. 타이머로 1초후 더미 -> 플레이어
이렇게 호출하면 나중에 할때처럼 작동 할 수 있을까?

**Comment by ParkSoonHong** [comment]
플레이어 -> 더미 지정하고
저 매칭 되었습니다를 1초 정도 있다가뜨게한다는 소리인가?

**Comment by ParkSoonHong** [comment]
아하 두명다 지정을 했을때 나중에 할때 처럼 작동 하게 할 수 있냐는 소리지?

**Comment by junsarakill** [comment]
지금 플레이어가 선택 결정하면
무조건 매칭되게 처리했다고 했는데,

내 쪽에서 플레이어 -> 더미 결정 이랑 더미 -> 플레이어 결정 두

ㅇㅇ

**Comment by ParkSoonHong** [comment]
아니 지금은 그렇게 안되어 있고 무조건 띄우게 되어있어서 수정이 필요한데 수정해서 올려줘?

**Comment by junsarakill** [comment]
응, 어차피 두 명 id 고정되어있으니깐 할 수 있을것 같아서

**Comment by ParkSoonHong** [comment]
오케이그럼 수정해서올릴게

**Comment by ParkSoonHong** [comment]
void APSH_Mtvs3rdGameModBase::ChekChoice() // 현재는 2명으로 구현되어 있음 4명일 때 UI 어떻게 보여줘야 하는지 잘 모르겠어서 추후 수정
{
	if (ChoiceWidget)
	{
		for (int i = 1; i < 3; i++)  // 전체 확인을 했기 때문에 3명을 검사 할 필요가 없다.
		{
			
			if (ChoiceNum[i] == 0) // 플레이어를 선택 안했거나 플레이어가 아님
			{
				continue;
			}
			else
			{
				if (ChoiceNum[i] == ChoiceNum[ChoiceNum[i]]) // 남자 1번과 누군가 자신을 선택했는지
				{
					ChoiceWidget->SuccessChoice();
				}
				else
				{
					ChoiceWidget->FailChoice();
				}
			}
		}

	}
}

2명일때는 어떻게 해야할지 알겠어서 했는데 4명일때 UI 부분에서 어떻게 해야할지 애메해서 일단 2명전부 선택하고 2명 전부선택했을때 비교해서 확인 한다음 성공하면성공 UI 일치하지않으면 실패 UI 로 만들었어

**Comment by junsarakill** [comment]
최종 선택 ui는 구현 했는데 
데이터 게임모드에 보내는건 자고 일어나서 할게

**Comment by junsarakill** [comment]
플레이어 선택 후 1.5초 뒤에 더미 id -> 플레이어 id 로 선택 보냄

**Comment by junsarakill** [comment]
종료
