### ISSUE TITLE
GM(게임모드)와 GI(게임모드 인스턴스) 데이터 반환 함수 추가

### ISSUE THREAD

**Issue by ParkSoonHong** [junsarakill/mtvs3rd#18]
FPSH_HttpDataTable APSH_Mtvs3rdGameModBase::GetData(int num)
{
	return Gi->GetData(num);
}

FPSH_HttpDataTable UPSH_GameInstance::GetData(int num)
{
	FString numstring = FString::FromInt(num);

	// 같은 Name으로 접근하면 덮어 씌워진다.
	FName RowName = FName(numstring); // 이름 저장 
	FPSH_HttpDataTable* FoundData = DataTable->FindRow<FPSH_HttpDataTable>(RowName, TEXT("Looking up player data"));

	return *FoundData;
}|

게임모드나 게임인스턴스에 접근해서GetData로 ID를 넣어서 실행시키면 해당 ID에 해당하는 값을 반환해줌

시연상태에서는 플레이어ID  = 1 , 더미ID = 0

더미 데이터는 임시로 만들어놓음 테이블에
만약 가져오는게 이상하면 일단 이걸로테스트 하고 이슈 댓글 달아줘

**Comment by junsarakill** [comment]
추가함
근데 mainmap에서 바로 시작하면 플레이어 state가 갱신이 안되는건가?
