### ISSUE TITLE
UI 찍어서 보내기

### ISSUE THREAD

**Issue by junsarakill** [junsarakill/mtvs3rd#24]
간트 정리 후 할 예정

**Comment by shirotanuLOW** [comment]
순홍이가 UI문서 정리해서 줬어!

**Comment by junsarakill** [comment]
플레이어 쪽 정리했어
[](https://drive.google.com/drive/folders/1Y7hsUZxuK1e2z2hvOGmAkw3QxdH8yUlB)

**Comment by junsarakill** [comment]
같은 폴더에 이벤트 쪽 도 올라왔고
미니게임 쪽 UI는 안정해져서 구조 정해지면 보낸대

확인하면 close 해줘
