### ISSUE TITLE
MiniGame 액터 6개 정리

### ISSUE THREAD

**Issue by jyunseon81** [junsarakill/mtvs3rd#32]
Shoes
Clothes
Hat
Bag
Muffler
Watch

총 6개의 선택지가 버튼으로 구현 되어있음

**Comment by junsarakill** [comment]
<img width="303" alt="KakaoTalk_20240925_152502707" src="https://github.com/user-attachments/assets/6172c7c8-2fcc-4926-9e32-06848927085f">

**Comment by junsarakill** [comment]
적용
